name: Montshe Mokgokong
title: Montshe's blog
email: mokgokongjohannes@gmail.com
theme: jekyll-theme-cayman
description: Hi there.. My name is Montshe J Mokgokong, I am on journey to software craftsmanship,I'll be writing about the things I've learned and the projects I've completed..Happy reading!
logo: "asserts/images/me.jpeg"

author_image: "assets/images/me.jpeg"
parallax_image_one: "assets/images/pen.jpeg"
parallax_image_two: "assets/images/keyboard.jpeg"
